//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CamCan.CamCanService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scenario", Namespace="http://schemas.datacontract.org/2004/07/CamCan_Service")]
    public partial class Scenario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<CamCan.CamCanService.Question> _questionsField;
        
        private int _sIDField;
        
        private string _textField;
        
        private string _videoLinkField;
        
        private System.Collections.Generic.List<CamCan.CamCanService.Question> questionsField;
        
        private int sIDField;
        
        private string textField;
        
        private string videoLinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CamCan.CamCanService.Question> _questions {
            get {
                return this._questionsField;
            }
            set {
                if ((object.ReferenceEquals(this._questionsField, value) != true)) {
                    this._questionsField = value;
                    this.RaisePropertyChanged("_questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _sID {
            get {
                return this._sIDField;
            }
            set {
                if ((this._sIDField.Equals(value) != true)) {
                    this._sIDField = value;
                    this.RaisePropertyChanged("_sID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _text {
            get {
                return this._textField;
            }
            set {
                if ((object.ReferenceEquals(this._textField, value) != true)) {
                    this._textField = value;
                    this.RaisePropertyChanged("_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _videoLink {
            get {
                return this._videoLinkField;
            }
            set {
                if ((object.ReferenceEquals(this._videoLinkField, value) != true)) {
                    this._videoLinkField = value;
                    this.RaisePropertyChanged("_videoLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CamCan.CamCanService.Question> questions {
            get {
                return this.questionsField;
            }
            set {
                if ((object.ReferenceEquals(this.questionsField, value) != true)) {
                    this.questionsField = value;
                    this.RaisePropertyChanged("questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sID {
            get {
                return this.sIDField;
            }
            set {
                if ((this.sIDField.Equals(value) != true)) {
                    this.sIDField = value;
                    this.RaisePropertyChanged("sID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string videoLink {
            get {
                return this.videoLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.videoLinkField, value) != true)) {
                    this.videoLinkField = value;
                    this.RaisePropertyChanged("videoLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/CamCan_Service")]
    public partial class Question : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _ansAField;
        
        private string _ansBField;
        
        private string _ansCField;
        
        private string _ansDField;
        
        private string _correctAnsField;
        
        private int _idField;
        
        private string _questionTextField;
        
        private string ansAField;
        
        private string ansBField;
        
        private string ansCField;
        
        private string ansDField;
        
        private string correctAnsField;
        
        private int idField;
        
        private string questionTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ansA {
            get {
                return this._ansAField;
            }
            set {
                if ((object.ReferenceEquals(this._ansAField, value) != true)) {
                    this._ansAField = value;
                    this.RaisePropertyChanged("_ansA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ansB {
            get {
                return this._ansBField;
            }
            set {
                if ((object.ReferenceEquals(this._ansBField, value) != true)) {
                    this._ansBField = value;
                    this.RaisePropertyChanged("_ansB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ansC {
            get {
                return this._ansCField;
            }
            set {
                if ((object.ReferenceEquals(this._ansCField, value) != true)) {
                    this._ansCField = value;
                    this.RaisePropertyChanged("_ansC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ansD {
            get {
                return this._ansDField;
            }
            set {
                if ((object.ReferenceEquals(this._ansDField, value) != true)) {
                    this._ansDField = value;
                    this.RaisePropertyChanged("_ansD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _correctAns {
            get {
                return this._correctAnsField;
            }
            set {
                if ((object.ReferenceEquals(this._correctAnsField, value) != true)) {
                    this._correctAnsField = value;
                    this.RaisePropertyChanged("_correctAns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _questionText {
            get {
                return this._questionTextField;
            }
            set {
                if ((object.ReferenceEquals(this._questionTextField, value) != true)) {
                    this._questionTextField = value;
                    this.RaisePropertyChanged("_questionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ansA {
            get {
                return this.ansAField;
            }
            set {
                if ((object.ReferenceEquals(this.ansAField, value) != true)) {
                    this.ansAField = value;
                    this.RaisePropertyChanged("ansA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ansB {
            get {
                return this.ansBField;
            }
            set {
                if ((object.ReferenceEquals(this.ansBField, value) != true)) {
                    this.ansBField = value;
                    this.RaisePropertyChanged("ansB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ansC {
            get {
                return this.ansCField;
            }
            set {
                if ((object.ReferenceEquals(this.ansCField, value) != true)) {
                    this.ansCField = value;
                    this.RaisePropertyChanged("ansC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ansD {
            get {
                return this.ansDField;
            }
            set {
                if ((object.ReferenceEquals(this.ansDField, value) != true)) {
                    this.ansDField = value;
                    this.RaisePropertyChanged("ansD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correctAns {
            get {
                return this.correctAnsField;
            }
            set {
                if ((object.ReferenceEquals(this.correctAnsField, value) != true)) {
                    this.correctAnsField = value;
                    this.RaisePropertyChanged("correctAns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string questionText {
            get {
                return this.questionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.questionTextField, value) != true)) {
                    this.questionTextField = value;
                    this.RaisePropertyChanged("questionText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CamCanService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/returnScenario", ReplyAction="http://tempuri.org/IService1/returnScenarioResponse")]
        System.IAsyncResult BeginreturnScenario(int id, System.AsyncCallback callback, object asyncState);
        
        CamCan.CamCanService.Scenario EndreturnScenario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/returnComleted", ReplyAction="http://tempuri.org/IService1/returnComletedResponse")]
        System.IAsyncResult BeginreturnComleted(int user, System.AsyncCallback callback, object asyncState);
        
        int EndreturnComleted(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/returnUser", ReplyAction="http://tempuri.org/IService1/returnUserResponse")]
        System.IAsyncResult BeginreturnUser(string user, string pass, System.AsyncCallback callback, object asyncState);
        
        int EndreturnUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CamCan.CamCanService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnScenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnScenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CamCan.CamCanService.Scenario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CamCan.CamCanService.Scenario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnComletedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnComletedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CamCan.CamCanService.IService1>, CamCan.CamCanService.IService1 {
        
        private BeginOperationDelegate onBeginreturnScenarioDelegate;
        
        private EndOperationDelegate onEndreturnScenarioDelegate;
        
        private System.Threading.SendOrPostCallback onreturnScenarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginreturnComletedDelegate;
        
        private EndOperationDelegate onEndreturnComletedDelegate;
        
        private System.Threading.SendOrPostCallback onreturnComletedCompletedDelegate;
        
        private BeginOperationDelegate onBeginreturnUserDelegate;
        
        private EndOperationDelegate onEndreturnUserDelegate;
        
        private System.Threading.SendOrPostCallback onreturnUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<returnScenarioCompletedEventArgs> returnScenarioCompleted;
        
        public event System.EventHandler<returnComletedCompletedEventArgs> returnComletedCompleted;
        
        public event System.EventHandler<returnUserCompletedEventArgs> returnUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CamCan.CamCanService.IService1.BeginreturnScenario(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnScenario(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CamCan.CamCanService.Scenario CamCan.CamCanService.IService1.EndreturnScenario(System.IAsyncResult result) {
            return base.Channel.EndreturnScenario(result);
        }
        
        private System.IAsyncResult OnBeginreturnScenario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((CamCan.CamCanService.IService1)(this)).BeginreturnScenario(id, callback, asyncState);
        }
        
        private object[] OnEndreturnScenario(System.IAsyncResult result) {
            CamCan.CamCanService.Scenario retVal = ((CamCan.CamCanService.IService1)(this)).EndreturnScenario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnScenarioCompleted(object state) {
            if ((this.returnScenarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnScenarioCompleted(this, new returnScenarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnScenarioAsync(int id) {
            this.returnScenarioAsync(id, null);
        }
        
        public void returnScenarioAsync(int id, object userState) {
            if ((this.onBeginreturnScenarioDelegate == null)) {
                this.onBeginreturnScenarioDelegate = new BeginOperationDelegate(this.OnBeginreturnScenario);
            }
            if ((this.onEndreturnScenarioDelegate == null)) {
                this.onEndreturnScenarioDelegate = new EndOperationDelegate(this.OnEndreturnScenario);
            }
            if ((this.onreturnScenarioCompletedDelegate == null)) {
                this.onreturnScenarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnScenarioCompleted);
            }
            base.InvokeAsync(this.onBeginreturnScenarioDelegate, new object[] {
                        id}, this.onEndreturnScenarioDelegate, this.onreturnScenarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CamCan.CamCanService.IService1.BeginreturnComleted(int user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnComleted(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CamCan.CamCanService.IService1.EndreturnComleted(System.IAsyncResult result) {
            return base.Channel.EndreturnComleted(result);
        }
        
        private System.IAsyncResult OnBeginreturnComleted(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int user = ((int)(inValues[0]));
            return ((CamCan.CamCanService.IService1)(this)).BeginreturnComleted(user, callback, asyncState);
        }
        
        private object[] OnEndreturnComleted(System.IAsyncResult result) {
            int retVal = ((CamCan.CamCanService.IService1)(this)).EndreturnComleted(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnComletedCompleted(object state) {
            if ((this.returnComletedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnComletedCompleted(this, new returnComletedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnComletedAsync(int user) {
            this.returnComletedAsync(user, null);
        }
        
        public void returnComletedAsync(int user, object userState) {
            if ((this.onBeginreturnComletedDelegate == null)) {
                this.onBeginreturnComletedDelegate = new BeginOperationDelegate(this.OnBeginreturnComleted);
            }
            if ((this.onEndreturnComletedDelegate == null)) {
                this.onEndreturnComletedDelegate = new EndOperationDelegate(this.OnEndreturnComleted);
            }
            if ((this.onreturnComletedCompletedDelegate == null)) {
                this.onreturnComletedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnComletedCompleted);
            }
            base.InvokeAsync(this.onBeginreturnComletedDelegate, new object[] {
                        user}, this.onEndreturnComletedDelegate, this.onreturnComletedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CamCan.CamCanService.IService1.BeginreturnUser(string user, string pass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnUser(user, pass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CamCan.CamCanService.IService1.EndreturnUser(System.IAsyncResult result) {
            return base.Channel.EndreturnUser(result);
        }
        
        private System.IAsyncResult OnBeginreturnUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            string pass = ((string)(inValues[1]));
            return ((CamCan.CamCanService.IService1)(this)).BeginreturnUser(user, pass, callback, asyncState);
        }
        
        private object[] OnEndreturnUser(System.IAsyncResult result) {
            int retVal = ((CamCan.CamCanService.IService1)(this)).EndreturnUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnUserCompleted(object state) {
            if ((this.returnUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnUserCompleted(this, new returnUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnUserAsync(string user, string pass) {
            this.returnUserAsync(user, pass, null);
        }
        
        public void returnUserAsync(string user, string pass, object userState) {
            if ((this.onBeginreturnUserDelegate == null)) {
                this.onBeginreturnUserDelegate = new BeginOperationDelegate(this.OnBeginreturnUser);
            }
            if ((this.onEndreturnUserDelegate == null)) {
                this.onEndreturnUserDelegate = new EndOperationDelegate(this.OnEndreturnUser);
            }
            if ((this.onreturnUserCompletedDelegate == null)) {
                this.onreturnUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnUserCompleted);
            }
            base.InvokeAsync(this.onBeginreturnUserDelegate, new object[] {
                        user,
                        pass}, this.onEndreturnUserDelegate, this.onreturnUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CamCan.CamCanService.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<CamCan.CamCanService.IService1>, CamCan.CamCanService.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<CamCan.CamCanService.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginreturnScenario(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("returnScenario", _args, callback, asyncState);
                return _result;
            }
            
            public CamCan.CamCanService.Scenario EndreturnScenario(System.IAsyncResult result) {
                object[] _args = new object[0];
                CamCan.CamCanService.Scenario _result = ((CamCan.CamCanService.Scenario)(base.EndInvoke("returnScenario", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginreturnComleted(int user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("returnComleted", _args, callback, asyncState);
                return _result;
            }
            
            public int EndreturnComleted(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("returnComleted", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginreturnUser(string user, string pass, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = user;
                _args[1] = pass;
                System.IAsyncResult _result = base.BeginInvoke("returnUser", _args, callback, asyncState);
                return _result;
            }
            
            public int EndreturnUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("returnUser", _args, result)));
                return _result;
            }
        }
    }
}
